CREATE DATABASE GERENCIAMENTOTAREFA
GO
USE GERENCIAMENTOTAREFA
GO
CREATE TABLE TAREFA (
    ID INT IDENTITY PRIMARY KEY,
    TITULO VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    DATACRIACAO DATETIME NOT NULL,
    STATUS INT NOT NULL
)
GO
CREATE TABLE USUARIO(
    ID INT IDENTITY PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
	LOGINUSUARIO VARCHAR(100) NOT NULL,
	SENHA VARCHAR(100) NOT NULL
)