CREATE DATABASE GERENCIAMENTOTAREFA;
GO
CREATE TABLE TAREFA (
    ID INT IDENTITY PRIMARY KEY,
    TITULO VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    DATACRIACAO DATETIME NOT NULL,
    STATUS INT NOT NULL
)